### ISSUE TITLE
Add playlist support. 

### ISSUE THREAD

**Issue by MJ10** [MJ10/Cosmo#3]
# Add support for playlists
* Implement method to load playlists from MediaStore in `LibrarySource.java`
* Create methods to store playlist songs in a collection to make them available from MediaBrowser in `LibraryProvider.java`
* Add methods to create browsable MediaItems for the playlist, along with item layout and fragment for displaying playlists in ViewPager on home screen

**Comment by MJ10** [comment]
Add Now Playing screen

**Comment by salman-bhai** [comment]
Is this Issue resolved?
Any description about it?

**Comment by MJ10** [comment]
@salman-bhai the issue is not yet resolved. Added description :)
